version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=postgres://postgres:1234@db:5432/shopper_test_prod
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shopper_test_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

